#!/bin/sh

testdir=$1

passes=0
fails=0

for testcase in `ls ${testdir}/*.xml`; do
	sh ${testdir}/test-xml $testcase
	ret=$?
	if [ ${ret} -eq 0 ]; then
		passes=`expr $passes + 1`
		echo ${testcase} PASSED
	else
		fails=`expr $fails + 1`
		echo ${testcase} FAILED
	fi
done

echo PASSES ${passes}
echo FAILS ${fails}

if [ ${fails} -ne 0 ]; then
	exit 1
fi


